version: '3'
 
services:
  n12:
    image: node:12-alpine
    container_name: "node12"
    restart: unless-stopped
    ports:
      - 4000:3000
    volumes:
      - ./data/app:/home/node/app
    working_dir: /home/node/app
    command: >
      sh -c "npm install -g pm2 && npm install && pm2-runtime server.js --watch"